const express = require("express");
const router = express.Router();
const auth = require("../middlewares/userAuth");
const { _login } = require("./controllers/login");
// const { forget } = require("./controller/forgotPassword");
// const { resetPassword } = require("./controller/resetPassword");
// const { uploadPic } = require("./controller/upload");
// const { changePassword } = require("./controller/changePassword");
const { _getUser } = require("./controllers/getUser");
const { _getUsers } = require("./controllers/getUsersList");
const { _editUser } = require("./controllers/editUser");
const { _signup } = require("./controllers/signup");
const { _deleteUser } = require("./controllers/deleteUser");
router.post("/login", _login);
router.post("/signup", _signup);
// router.post("/forgotPassword", forget);
// router.post("/resetPassword", resetPassword);
// router.post("/changePassword", auth([1, 2]), changePassword);
router.get("/getUserList", auth(["ADMIN"]), _getUsers);
router.get("/getUser", auth(["USER","ADMIN"]), _getUser);
router.get("/deleteUser", auth(["ADMIN"]), _deleteUser);
router.post("/editUser", auth(["USER", "ADMIN"]), _editUser);

module.exports = router;
